// images
import blogImg1 from "../images/blog/img-10.jpg";
import blogImg2 from "../images/blog/img-11.jpg";
import blogImg3 from "../images/blog/img-12.jpg";

import blogSingleImg1 from "../images/blog/img-10.jpg";
import blogSingleImg2 from "../images/blog/img-11.jpg";
import blogSingleImg3 from "../images/blog/img-12.jpg";

import lifstyle1 from '../images/lifestyle/img-1.jpg' 
import lifstyle2 from '../images/lifestyle/img-2.jpg' 
import lifstyle3 from '../images/lifestyle/img-3.jpg' 

import Food1 from '../images/foods/img-1.jpg' 
import Food2 from '../images/foods/img-2.jpg' 
import Food3 from '../images/foods/img-3.jpg' 

import Business1 from '../images/business/img-1.jpg' 
import Business2 from '../images/business/img-2.jpg' 
import Business3 from '../images/business/img-3.jpg' 

const Blogs = [
    {
        id: '1',
        title: 'யோர்தான் ஆற்றில் இயேசு நன்செய்த இடம்: பெத்தானி பயணம்',
        slug:"Visiting-Bethany",
        screens: blogImg1,
        thumb:'ஆன்மிகம்',
        description: 'இந்த கட்டுரையில் வரலாற்று முக்கியத்துவம் வாய்ந்த இடம் குறித்து விரிவாக பார்க்கலாம்.',
        author: 'மாரிலோ கேலெஹர்',
        authorTitle:'மூத்த ஆலோசகர்',
        create_at: '25 டிசம்பர், 2023',
        blogSingleImg:blogSingleImg1, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '2',
        title: 'சிறு தொழில்முனைவோரின் வெற்றிக் குறிப்புகள்',
        slug:"Tips-From-Successful",
        thumb:'வணிகம்',
        author: 'கோனல் பிரி',
        authorTitle:'படைப்பு இயக்குநர்',
        create_at: '13 டிசம்பர், 2022',
        comment:'80',
        blClass:'format-standard',
    },
    {
        id: '3',
        title: 'துருக்கி: கப்பதோக்கியாவின் ஜெரோம் நகரில் செய்ய வேண்டிய 5 விஷயங்கள்',
        slug:"Turkey",
        screens: blogImg2,
        thumb:'பயணம்',
        description: 'பயணிகளுக்கு சிறந்த வழிகாட்டி.',
        author: 'அலிசா',
        authorTitle:'கலை இயக்குநர்',
        create_at: '22 டிசம்பர், 2022',
        blogSingleImg:blogSingleImg2,
        comment:'95',
        blClass:'format-standard-image',
    },
    {
        id: '4',
        title: 'துருக்கி செல்ல வேண்டிய 10 காரணங்கள்',
        slug:"10-Reasons",
        screens: blogImg3,
        thumb:'பயணம்',
        description: 'பயண அனுபவத்தை செழுமையாக்கும் முக்கிய அம்சங்கள்.',
        author: 'மாரிலோ கேலெஹர்',
        authorTitle:'மூத்த ஆலோசகர்',
        create_at: '25 டிசம்பர், 2023',
        blogSingleImg:blogSingleImg3, 
        comment:'35',
        blClass:'format-video',
    },
    {
        id: '5',
        title: 'வாரத்தின் சிறந்த தொடக்கத்திற்கான ஞாயிறு இரவு பழக்கம்',
        slug:"A-Sunday-night-routine",
        screens: lifstyle1,
        thumb:'வாழ்க்கை முறை',
        description: 'வாழ்க்கை தரத்தை மேம்படுத்த சிறந்த வழிமுறைகள்.',
        author: 'மாரிலோ கேலெஹர்',
        authorTitle:'மூத்த ஆலோசகர்',
        create_at: '25 டிசம்பர், 2023',
        blogSingleImg:lifstyle1, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '6',
        title: 'மன அழுத்தத்தை சமாளிக்கும் சிறந்த முறைகள்',
        slug:"deal-with-stress",
        thumb:'வாழ்க்கை முறை',
        author: 'கோனல் பிரி',
        authorTitle:'படைப்பு இயக்குநர்',
        create_at: '13 டிசம்பர், 2022',
        comment:'80',
        blClass:'format-standard',
    },
    {
        id: '7',
        title: 'உங்கள் நகரில் செய்ய வேண்டிய 10 சிறந்த செயல்கள்',
        slug:"regional-area",
        screens: lifstyle2,
        thumb:'பயணம்',
        description: 'உள்ளூர் வாழ்க்கை மற்றும் சுற்றுலா அனுபவங்கள்.',
        author: 'அலிசா',
        authorTitle:'கலை இயக்குநர்',
        create_at: '22 டிசம்பர், 2022',
        blogSingleImg:lifstyle2,
        comment:'95',
        blClass:'format-standard-image',
    },
    {
        id: '8',
        title: 'Instagram கணக்கை வளர்ப்பதற்கான உங்கள் குறிப்புகள்',
        slug:"Instagram-account",
        screens: lifstyle3,
        thumb:'தொழில்நுட்பம்',
        description: 'சமூக ஊடக வளர்ச்சிக்கான நடைமுறை வழிகள்.',
        author: 'மாரிலோ கேலெஹர்',
        authorTitle:'மூத்த ஆலோசகர்',
        create_at: '25 டிசம்பர், 2023',
        blogSingleImg:lifstyle3, 
        comment:'35',
        blClass:'format-video',
    },
    {
        id: '9',
        title: 'உள்ளூர் மற்றும் சர்வதேச உணவக நிகழ்வுகள்',
        slug:"internationally",
        screens: Food1,
        thumb:'உணவு',
        description: 'சமையல் கலாச்சாரம் மற்றும் உணவு விழாக்கள்.',
        author: 'மாரிலோ கேலெஹர்',
        authorTitle:'மூத்த ஆலோசகர்',
        create_at: '25 டிசம்பர், 2023',
        blogSingleImg:Food1, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '10',
        title: 'சமையலறை குழுவுடன் நேர்காணல்',
        slug:"Interview",
        thumb:'உணவு',
        author: 'கோனல் பிரி',
        authorTitle:'படைப்பு இயக்குநர்',
        create_at: '13 டிசம்பர், 2022',
        comment:'80',
        blClass:'format-standard',
    },
    {
        id: '11',
        title: 'சிறப்பு நிகழ்வுகளுக்கான சிறந்த உணவகங்கள் பட்டியல்',
        slug:"specific-occasion",
        screens: Food2,
        thumb:'உணவு',
        description: 'சுவையான அனுபவத்திற்கு பரிந்துரைகள்.',
        author: 'மாரிலோ கேலெஹர்',
        authorTitle:'மூத்த ஆலோசகர்',
        create_at: '25 டிசம்பர், 2023',
        blogSingleImg:Food2, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '12',
        title: 'சிறப்பு சமையல் குறிப்புகள்: உணவகங்கள் & சமையலர்கள்',
        slug:"Exclusive-recipes",
        screens: Food3,
        thumb:'உணவு',
        description: 'வித்தியாசமான சுவை அனுபவங்கள்.',
        author: 'அலிசா',
        authorTitle:'கலை இயக்குநர்',
        create_at: '22 டிசம்பர், 2022',
        blogSingleImg:Food3,
        comment:'95',
        blClass:'format-video',
    },
    {
        id: '13',
        title: 'தொழில் தொடங்கும் போது நிறுவுநர்கள் செய்யும் 8 தவறுகள்',
        slug:"8-Mistakes-Founders",
        screens: Business1,
        thumb:'வணிகம்',
        description: 'புதிய நிறுவனங்களுக்கு முக்கிய எச்சரிக்கைகள்.',
        author: 'மாரிலோ கேலெஹர்',
        authorTitle:'மூத்த ஆலோசகர்',
        create_at: '25 டிசம்பர், 2023',
        blogSingleImg:Business1, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '14',
        title: 'வெற்றி பெற்ற சிறு தொழில்முனைவோரின் ஆலோசனைகள்',
        slug:"Small-Business",
        thumb:'வணிகம்',
        author: 'கோனல் பிரி',
        authorTitle:'படைப்பு இயக்குநர்',
        create_at: '13 டிசம்பர், 2022',
        comment:'80',
        blClass:'format-standard',
    },
    {
        id: '15',
        title: 'சிறு தொழில்கள் மார்க்கெட்டிங்கில் பணத்தை வீணடிக்கும் வழிகள்',
        slug:"Waste-Money",
        screens: Business2,
        thumb:'வணிகம்',
        description: 'சிக்கனமாக செயல்பட வேண்டிய முக்கிய அம்சங்கள்.',
        author: 'மாரிலோ கேலெஹர்',
        authorTitle:'மூத்த ஆலோசகர்',
        create_at: '25 டிசம்பர், 2023',
        blogSingleImg:Business2, 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '16',
        title: 'மேலாண்மை ஆலோசனையை ஏன் தேர்வு செய்ய வேண்டும்?',
        slug:"Consulting",
        screens: Business3,
        thumb:'வணிகம்',
        description: 'ஆலோசனைத் துறையின் முக்கியத்துவம் மற்றும் வாய்ப்புகள்.',
        author: 'அலிசா',
        authorTitle:'கலை இயக்குநர்',
        create_at: '22 டிசம்பர், 2022',
        blogSingleImg:Business3,
        comment:'95',
        blClass:'format-video',
    },
];
export default Blogs;
